spring:
  kafka:
    consumer:
      group-id: palmetto-data
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092

# Port config
server:
  port: 8081

# For Kafka implementation
tpd:
  order-topic: orders
  notification-topic: notifications