spring:
  kafka:
    producer:
      acks: 1
      retries: 1
    consumer:
      group-id: palmetto-data
      auto-offset-reset: earliest
      enable-auto-commit: false
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092

# Port config
server:
  port: 8082

# For Kafka implementation
tpd:
  order-topic: orders
  notification-topic: notifications